# -*- coding: utf-8 -*-
#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
import sphinx_bootstrap_theme
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = u' '
copyright = u'2016-2019 by Effective Quadratures'
author = u'Pranay Seshadri, Nicholas Wong, James Gross, Irene Vidris'

# The short X.Y version
version = u'8.0'
# The full version, including alpha/beta/rc tags
release = u'v8.0'


# -- General configuration ---------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.doctest',
    'sphinx.ext.intersphinx',
    'sphinx.ext.todo',
    'sphinx.ext.coverage',
    'sphinx.ext.mathjax',
    'sphinx.ext.ifconfig',
    'sphinx.ext.viewcode',
    'sphinx.ext.githubpages',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_docstemplates']

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = '.txt'

# The master toctree document.
master_doc = '_documentation/index'
#html_theme = "sphinx_rtd_theme"
#html_theme_path = ["_themes", ]

html_theme = 'bootstrap'
html_theme_path = sphinx_bootstrap_theme.get_html_theme_path()
#html_theme_options = {
#    'style_nav_header_background': 'grey',
#}

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = [u'_docsbuild', 'Thumbs.db', '.DS_Store']

# The name of the Pygments (syntax highlighting) style to use.
#pygments_style = 'sphinx'


# -- Options for HTML output -------------------------------------------------


# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ['']

html_logo = 'logo_white_font.png'
html_favicon = 'logo.png'
# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# The default sidebars (for documents that don't match any pattern) are
# defined by theme itself.  Builtin themes are using these templates by
# default: ``['localtoc.html', 'relations.html', 'sourcelink.html',
# 'searchbox.html']``.
#
# html_sidebars = {}


# -- Options for HTMLHelp output ---------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = 'EffectiveQuadraturesdoc'


# -- Options for LaTeX output ------------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    'papersize': 'a4paper',

    # The font size ('10pt', '11pt' or '12pt').
    #
    'pointsize': '12pt',

    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',

    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, 'EffectiveQuadratures.tex', u'Effective Quadratures Documentation',
     u'Pranay Seshadri, Nicholas Wong, Henry Yuchi, Irene Virdis', 'manual'),
]


# -- Options for manual page output ------------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [
    (master_doc, 'effectivequadratures', u'Effective Quadratures Documentation',
     [author], 1)
]


# -- Options for Texinfo output ----------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (master_doc, 'EffectiveQuadratures', u' ',
     author, 'EffectiveQuadratures', 'One line description of project.',
     'Miscellaneous'),
]


# -- Extension configuration -------------------------------------------------

# -- Options for intersphinx extension ---------------------------------------

# Example configuration for intersphinx: refer to the Python standard library.
intersphinx_mapping = {'https://docs.python.org/': None}

# -- Options for todo extension ----------------------------------------------

# If true, `todo` and `todoList` produce output, else they produce nothing.
#todo_include_todos = True

html_theme_options = {
    # Navigation bar title. (Default: ``project`` value)
    'navbar_title': "",
    
    # Tab name for entire site. (Default: "Site")
    'navbar_site_name': "Explore",
    
    # A list of tuples containing pages or urls to link to.
    # Valid tuples should be in the following forms:
    #    (name, page)                 # a link to a page
    #    (name, "/aa/bb", 1)          # a link to an arbitrary relative url
    #    (name, "http://example.com", True) # arbitrary absolute url
    # Note the "1" or "True" value above as the third argument to indicate
    # an arbitrary url.
    'navbar_links': [
                     #("Examples", "examples"),
                     ],
        
                     # Render the next and previous page links in navbar. (Default: true)
                     'navbar_sidebarrel': False,
                     
                     # Render the current pages TOC in the navbar. (Default: true)
                     'navbar_pagenav': False,
                     
                     # Tab name for the current pages TOC. (Default: "Page")
                     #'navbar_pagenav_name': "Page",
                     
                     # Global TOC depth for "site" navbar tab. (Default: 1)
                     # Switching to -1 shows all levels.
                     'globaltoc_depth': -1,
                     
                     # Include hidden TOCs in Site navbar?
                     #
                     # Note: If this is "false", you cannot have mixed ``:hidden:`` and
                     # non-hidden ``toctree`` directives in the same page, or else the build
                     # will break.
                     #
                     # Values: "true" (default) or "false"
                     'globaltoc_includehidden': "true",
                     
                     # HTML navbar class (Default: "navbar") to attach to <div> element.
                     # For black navbar, do "navbar navbar-inverse"
                     'navbar_class': "navbar",
                     
                     # Fix navigation bar to top of page?
                     # Values: "true" (default) or "false"
                     'navbar_fixed_top': "true",
                     
                     # Location of link to source.
                     # Options are "nav" (default), "footer" or anything else to exclude.
                     'source_link_position': "none",
                     
                     # Bootswatch (http://bootswatch.com/) theme.
                     #
                     # Options are nothing (default) or the name of a valid theme
                     # such as "cosmo" or "sandstone".
                     #
                     # The set of valid themes depend on the version of Bootstrap
                     # that's used (the next config option).
                     #
                     # Currently, the supported themes are:
                     # - Bootstrap 2: https://bootswatch.com/2
                     # - Bootstrap 3: https://bootswatch.com/3
                     'bootswatch_theme': "cerulean",
                     'page_toc_position': 'sidebar-left',
                     
                     # Choose Bootstrap version.
                     # Values: "3" (default) or "2" (in quotes)
    'bootstrap_version': "3",
}
